name: Guilds

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Guilds.yml'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  Guilds:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "guilds-plugin/Guilds"
      target: "build/libs/*.jar"
      name: "Guilds"
      java: 8  # Đổi về Java 8 vì có thể project yêu cầu Java 8
      distribution: "temurin"
      commands: |
        chmod +x ./gradlew
        # Thêm checksum vào gradle-wrapper.properties
        echo "distributionSha256Sum=e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637" >> gradle/wrapper/gradle-wrapper.properties
        # Đảm bảo dependencies được resolve đúng
        ./gradlew --refresh-dependencies
      tasks: "clean build -x test"  # Bỏ qua tests để tránh lỗi
      readonly: true
      cache: "guilds"
      version: "7.3.3"  # Chỉ định version Gradle cụ thể
      dir: "."  # Build từ thư mục gốc
