name: QualityArmoryVehicles2

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/QAV2.yml'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  QAV2:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "ZombieStriker/QualityArmoryVehicles2"
      target: "build/libs/*.jar"
      name: "QualityArmoryVehicles2"
      java: 8
      distribution: "temurin"
      commands: |
        chmod +x ./gradlew
        chmod +x ./gradle/wrapper/gradle-wrapper.jar
        # Cập nhật version của shadow plugin trong build.gradle.kts
        sed -i 's/com.github.johnrengelman.shadow\" version \"8.1.1/com.github.johnrengelman.shadow\" version \"7.1.2/g' build.gradle.kts
        # Refresh dependencies
        ./gradlew --refresh-dependencies
      tasks: "clean shadowJar"
      readonly: true
      cache: "qav2"
      version: "8.0"  # Nâng lên Gradle 8.0 để phù hợp với Shadow plugin
