name: QualityArmoryVehicles2

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/QAV2.yml'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  QAV2:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "ZombieStriker/QualityArmoryVehicles2"
      target: "build/libs/*.jar"
      name: "QualityArmoryVehicles2"
      java: 8
      distribution: "temurin"
      commands: |
        chmod +x ./gradlew
        chmod +x ./gradle/wrapper/gradle-wrapper.jar
        # Đảm bảo kết nối với Maven repositories
        export MAVEN_OPTS="-Xmx2048m"
        export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000"
        ./gradlew --refresh-dependencies --info --stacktrace --configure-on-demand properties
      tasks: "clean build shadowJar --stacktrace --info"
      readonly: false
      cache: "qav2"
      version: "wrapper"
      dir: "."
      os: "ubuntu-latest"
    env:
      # Thêm các maven repositories vào environment
      MAVEN_REPO_URL: |
        https://hub.spigotmc.org/nexus/content/repositories/snapshots/
        https://oss.sonatype.org/content/repositories/snapshots/
        https://repo.dmulloy2.net/repository/public/
        https://jitpack.io
        https://maven.enginehub.org/repo/
      MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      MAVEN_OPTS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2048m"
